export const teamTemplates = [
  // ═══════════════════════════════════════════════════════════════
  // HEALTHCARE (2 team templates)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Care Coordination Team",
    description: "End-to-end patient care coordination from intake triage through clinical documentation, prior authorization, and care gap identification. Orchestrates sequential handoffs across four specialized agents to ensure continuity of care while maintaining HIPAA compliance at every step.",
    category: "team_workflow",
    industry: "healthcare",
    tags: ["team", "care-coordination", "multi-agent", "hipaa", "sequential"],
    icon: "users",
    complexity: "high",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "HIGH",
    defaultAutonomyMode: "assisted",
    complianceCertifications: ["HIPAA", "HITRUST"],
    deploymentCount: 12,
    avgKpiDelivery: 87,
    estimatedTimeToProd: "3-5 weeks",
    toolsConfig: [
      { name: "patient_intake_system", description: "Reads patient intake forms and triage data from EHR", permissions: ["patients:read"] },
      { name: "ehr_documentation_writer", description: "Writes clinical documentation and notes to the EHR system", permissions: ["ehr:write"] },
      { name: "prior_auth_submitter", description: "Submits prior authorization requests to insurance payers", permissions: ["authorizations:write"] },
      { name: "care_gap_analyzer", description: "Analyzes patient records for gaps in preventive care and follow-ups", permissions: ["analytics:read", "patients:read"] },
      { name: "patient_notification_sender", description: "Sends patient outreach messages for care gaps and follow-ups", permissions: ["notifications:send"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Triage Agent", role: "intake", skills: ["patient-assessment", "priority-classification", "symptom-analysis"] },
        { name: "Clinical Documentation Agent", role: "documentation", skills: ["medical-coding", "note-generation", "ehr-integration"] },
        { name: "Prior Auth Agent", role: "authorization", skills: ["insurance-verification", "prior-auth-submission", "approval-tracking"] },
        { name: "Care Gap Agent", role: "follow-up", skills: ["gap-detection", "patient-outreach", "care-plan-monitoring"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "PHI Minimization", description: "Each agent receives only the PHI it needs to perform its specific function", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
        { name: "Minimum Necessary Standard", description: "Data shared between agents is limited to the minimum necessary for the intended purpose", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
        { name: "De-identification Between Non-Clinical Agents", description: "PHI is de-identified when passed to agents that do not require clinical context", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
        { name: "Audit Trail for All PHI Access", description: "Complete audit log maintained for every agent access to protected health information", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
      ],
      federationTrust: {
        trustTier: "VERIFIED",
        requirements: [
          { name: "Business Associate Agreement (BAA)", description: "Legally binding BAA required before any PHI data exchange with external agents", status: "required", documentType: "Legal Agreement" },
          { name: "HITRUST Certification", description: "HITRUST CSF certification preferred for external agent providers", status: "recommended", documentType: "Certification" },
          { name: "PHI Data Handling Attestation", description: "Formal attestation of PHI handling practices and safeguards", status: "required", documentType: "Attestation" },
          { name: "Breach Notification SLA (72h)", description: "72-hour breach notification SLA for any PHI exposure incidents", status: "required", documentType: "SLA" },
        ],
      },
    },
    policyBindings: [
      { policyName: "HIPAA Privacy Rule Compliance", enforcement: "hard" },
      { policyName: "PHI Access Logging", enforcement: "hard" },
      { policyName: "Patient Consent Verification", enforcement: "hard" },
    ],
  },
  {
    name: "Clinical Trial Management Team",
    description: "Multi-agent pipeline for clinical trial protocol management, patient screening and enrollment, adverse event monitoring, and regulatory submission preparation. Ensures GCP compliance and FDA 21 CFR Part 11 adherence throughout the trial lifecycle.",
    category: "team_workflow",
    industry: "healthcare",
    tags: ["team", "clinical-trials", "multi-agent", "hipaa", "gcp", "sequential"],
    icon: "users",
    complexity: "high",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "HIGH",
    defaultAutonomyMode: "manual",
    complianceCertifications: ["HIPAA", "HITRUST", "FDA-21CFR11"],
    deploymentCount: 6,
    avgKpiDelivery: 82,
    estimatedTimeToProd: "6-8 weeks",
    toolsConfig: [
      { name: "protocol_manager", description: "Manages clinical trial protocol documents and amendments", permissions: ["protocols:read", "protocols:write"] },
      { name: "patient_screener", description: "Screens patients against inclusion/exclusion criteria", permissions: ["patients:read", "eligibility:compute"] },
      { name: "adverse_event_reporter", description: "Records and classifies adverse events per MedDRA coding", permissions: ["adverse_events:write", "safety:read"] },
      { name: "regulatory_submission_api", description: "Prepares and submits regulatory documents to FDA/EMA portals", permissions: ["submissions:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Protocol Design Agent", role: "protocol", skills: ["protocol-authoring", "endpoint-definition", "randomization-design"] },
        { name: "Patient Screening Agent", role: "enrollment", skills: ["eligibility-screening", "consent-management", "cohort-matching"] },
        { name: "Adverse Event Monitor Agent", role: "safety", skills: ["ae-detection", "meddra-coding", "safety-signal-analysis"] },
        { name: "Regulatory Submission Agent", role: "submission", skills: ["ctd-formatting", "fda-submission", "ema-submission"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "PHI Minimization", description: "Each agent receives only the PHI it needs to perform its specific function", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
        { name: "Minimum Necessary Standard", description: "Data shared between agents is limited to the minimum necessary for the intended purpose", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
        { name: "De-identification Between Non-Clinical Agents", description: "PHI is de-identified when passed to agents that do not require clinical context", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
        { name: "Audit Trail for All PHI Access", description: "Complete audit log maintained for every agent access to protected health information", enforcement: "STRICT", regulation: "HIPAA Privacy Rule" },
      ],
      federationTrust: {
        trustTier: "VERIFIED",
        requirements: [
          { name: "Business Associate Agreement (BAA)", description: "Legally binding BAA required before any PHI data exchange with external agents", status: "required", documentType: "Legal Agreement" },
          { name: "HITRUST Certification", description: "HITRUST CSF certification preferred for external agent providers", status: "recommended", documentType: "Certification" },
          { name: "PHI Data Handling Attestation", description: "Formal attestation of PHI handling practices and safeguards", status: "required", documentType: "Attestation" },
          { name: "Breach Notification SLA (72h)", description: "72-hour breach notification SLA for any PHI exposure incidents", status: "required", documentType: "SLA" },
        ],
      },
    },
    policyBindings: [
      { policyName: "HIPAA Privacy Rule Compliance", enforcement: "hard" },
      { policyName: "GCP (Good Clinical Practice)", enforcement: "hard" },
      { policyName: "FDA 21 CFR Part 11", enforcement: "hard" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // FINANCIAL SERVICES (2 team templates)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Client Onboarding Team",
    description: "Regulated client onboarding pipeline from identity verification through suitability assessment, account provisioning, and compliance sign-off. Ensures BSA/AML and KYC requirements are met at every stage with full audit trail.",
    category: "team_workflow",
    industry: "financial_services",
    tags: ["team", "onboarding", "multi-agent", "kyc", "compliance", "sequential"],
    icon: "users",
    complexity: "high",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "HIGH",
    defaultAutonomyMode: "assisted",
    complianceCertifications: ["SOC2", "SOX", "BSA-AML"],
    deploymentCount: 18,
    avgKpiDelivery: 91,
    estimatedTimeToProd: "4-6 weeks",
    toolsConfig: [
      { name: "id_verification_service", description: "Validates government-issued IDs and performs liveness checks", permissions: ["documents:verify"] },
      { name: "sanctions_screener", description: "Screens applicants against OFAC, UN, and EU sanctions lists", permissions: ["sanctions_lists:read"] },
      { name: "suitability_assessor", description: "Evaluates client risk profile and investment suitability", permissions: ["risk_profiles:compute"] },
      { name: "account_provisioning_api", description: "Creates accounts and assigns products based on client classification", permissions: ["accounts:write"] },
      { name: "compliance_workflow_engine", description: "Manages compliance review workflow and audit trail generation", permissions: ["compliance:write", "audit:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "KYC Agent", role: "verification", skills: ["identity-verification", "document-validation", "sanctions-screening"] },
        { name: "Suitability Agent", role: "assessment", skills: ["risk-profiling", "investment-suitability", "client-classification"] },
        { name: "Account Setup Agent", role: "provisioning", skills: ["account-creation", "product-assignment", "access-provisioning"] },
        { name: "Compliance Review Agent", role: "compliance", skills: ["regulatory-check", "audit-trail", "approval-workflow"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "Chinese Wall Enforcement", description: "Strict information barriers between advisory and trading agents to prevent conflicts of interest", enforcement: "STRICT", regulation: "SEC/FINRA" },
        { name: "Need-to-Know Data Compartmentalization", description: "Agent data access restricted to information required for assigned tasks only", enforcement: "STRICT", regulation: "SEC/FINRA" },
        { name: "MNPI Barriers", description: "Material non-public information barriers enforced across all agent communications", enforcement: "STRICT", regulation: "SEC/FINRA" },
        { name: "Client Data Segregation", description: "Complete segregation of client data between agents serving different clients", enforcement: "STRICT", regulation: "SEC/FINRA" },
      ],
      federationTrust: {
        trustTier: "CERTIFIED",
        requirements: [
          { name: "Data Processing Agreement", description: "Comprehensive data processing agreement covering all financial data types", status: "required", documentType: "Legal Agreement" },
          { name: "SOC 2 Type II Certification", description: "SOC 2 Type II audit report required for external agent infrastructure", status: "required", documentType: "Certification" },
          { name: "Regulatory Reporting Capability", description: "External agents must support regulatory reporting requirements", status: "recommended", documentType: "Technical Specification" },
          { name: "Financial Data Residency", description: "Financial data residency requirements for cross-border agent federation", status: "required", documentType: "Compliance Document" },
        ],
      },
    },
    policyBindings: [
      { policyName: "BSA/AML Compliance", enforcement: "hard" },
      { policyName: "KYC Verification Standards", enforcement: "hard" },
      { policyName: "Client Suitability Requirements", enforcement: "hard" },
    ],
  },
  {
    name: "Fraud Detection & Response Team",
    description: "Real-time multi-agent fraud detection pipeline combining transaction monitoring, behavioral analytics, investigation triage, and automated response actions. Coordinates sequential analysis with parallel alert routing for time-sensitive fraud mitigation.",
    category: "team_workflow",
    industry: "financial_services",
    tags: ["team", "fraud-detection", "multi-agent", "real-time", "compliance", "sequential"],
    icon: "users",
    complexity: "high",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "HIGH",
    defaultAutonomyMode: "assisted",
    complianceCertifications: ["SOC2", "PCI-DSS", "BSA-AML"],
    deploymentCount: 22,
    avgKpiDelivery: 93,
    estimatedTimeToProd: "4-6 weeks",
    toolsConfig: [
      { name: "transaction_stream_monitor", description: "Monitors real-time transaction streams for anomalous patterns", permissions: ["transactions:read"] },
      { name: "behavioral_analytics_engine", description: "Analyzes user behavioral patterns against established baselines", permissions: ["analytics:compute", "user_profiles:read"] },
      { name: "case_management_system", description: "Creates and manages fraud investigation cases with evidence collection", permissions: ["cases:write"] },
      { name: "account_action_manager", description: "Executes account holds, blocks, and automated response actions", permissions: ["accounts:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Transaction Monitor Agent", role: "monitoring", skills: ["real-time-scoring", "anomaly-detection", "velocity-checks"] },
        { name: "Behavioral Analytics Agent", role: "analysis", skills: ["behavioral-profiling", "device-fingerprinting", "geo-analysis"] },
        { name: "Investigation Triage Agent", role: "triage", skills: ["case-prioritization", "evidence-compilation", "siu-routing"] },
        { name: "Response Action Agent", role: "response", skills: ["account-holds", "alert-dispatch", "customer-notification"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "Chinese Wall Enforcement", description: "Strict information barriers between advisory and trading agents to prevent conflicts of interest", enforcement: "STRICT", regulation: "SEC/FINRA" },
        { name: "Need-to-Know Data Compartmentalization", description: "Agent data access restricted to information required for assigned tasks only", enforcement: "STRICT", regulation: "SEC/FINRA" },
        { name: "MNPI Barriers", description: "Material non-public information barriers enforced across all agent communications", enforcement: "STRICT", regulation: "SEC/FINRA" },
        { name: "Client Data Segregation", description: "Complete segregation of client data between agents serving different clients", enforcement: "STRICT", regulation: "SEC/FINRA" },
      ],
      federationTrust: {
        trustTier: "CERTIFIED",
        requirements: [
          { name: "Data Processing Agreement", description: "Comprehensive data processing agreement covering all financial data types", status: "required", documentType: "Legal Agreement" },
          { name: "SOC 2 Type II Certification", description: "SOC 2 Type II audit report required for external agent infrastructure", status: "required", documentType: "Certification" },
          { name: "Regulatory Reporting Capability", description: "External agents must support regulatory reporting requirements", status: "recommended", documentType: "Technical Specification" },
          { name: "Financial Data Residency", description: "Financial data residency requirements for cross-border agent federation", status: "required", documentType: "Compliance Document" },
        ],
      },
    },
    policyBindings: [
      { policyName: "PCI-DSS Data Handling", enforcement: "hard" },
      { policyName: "Transaction Hold Limits", enforcement: "hard" },
      { policyName: "SAR Filing Timelines", enforcement: "hard" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // MANUFACTURING (2 team templates)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Quality Assurance Team",
    description: "Closed-loop quality management pipeline from automated defect detection through root cause analysis and corrective action verification. Ensures continuous process improvement with full traceability to IEC 62443 and ITAR requirements.",
    category: "team_workflow",
    industry: "manufacturing",
    tags: ["team", "quality-assurance", "multi-agent", "capa", "sequential"],
    icon: "users",
    complexity: "medium",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "MEDIUM",
    defaultAutonomyMode: "assisted",
    complianceCertifications: ["ISO-9001", "IEC-62443"],
    deploymentCount: 15,
    avgKpiDelivery: 89,
    estimatedTimeToProd: "2-4 weeks",
    toolsConfig: [
      { name: "visual_inspection_system", description: "Performs automated visual inspection using computer vision models", permissions: ["inspection:read", "images:read"] },
      { name: "measurement_analyzer", description: "Analyzes dimensional measurements against specification tolerances", permissions: ["measurements:read"] },
      { name: "rca_knowledge_base", description: "Queries historical failure modes and root cause knowledge base", permissions: ["knowledge:read"] },
      { name: "capa_workflow_engine", description: "Creates and tracks corrective and preventive action workflows", permissions: ["capa:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Inspection Agent", role: "detection", skills: ["visual-inspection", "measurement-analysis", "defect-classification"] },
        { name: "Root Cause Agent", role: "analysis", skills: ["root-cause-analysis", "failure-mode-analysis", "trend-detection"] },
        { name: "Corrective Action Agent", role: "remediation", skills: ["capa-generation", "process-adjustment", "verification-testing"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "OT/IT Data Boundary Enforcement", description: "Operational technology data separated from IT systems with controlled interfaces", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
        { name: "Safety-Critical Data Isolation", description: "Safety-critical data isolated from general analytics to prevent unauthorized access", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
        { name: "IP Protection for Process Parameters", description: "Intellectual property and proprietary process parameters encrypted and access-controlled", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
        { name: "Air-Gap Compliance for Classified Data", description: "Classified manufacturing data maintained in air-gapped environments with no external agent access", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
      ],
      federationTrust: {
        trustTier: "VERIFIED",
        requirements: [
          { name: "IP Protection Agreement", description: "Intellectual property protection agreement for manufacturing process data", status: "required", documentType: "Legal Agreement" },
          { name: "Export Control Compliance (ITAR/EAR)", description: "Compliance with ITAR and EAR export control regulations", status: "required", documentType: "Compliance Document" },
          { name: "On-Premise Deployment Option", description: "On-premise deployment option required for classified manufacturing work", status: "recommended", documentType: "Technical Specification" },
          { name: "Supply Chain Security Attestation", description: "Supply chain security attestation for hardware and software components", status: "optional", documentType: "Attestation" },
        ],
      },
    },
    policyBindings: [
      { policyName: "ISO 9001 Quality Standards", enforcement: "hard" },
      { policyName: "CAPA Documentation Requirements", enforcement: "hard" },
      { policyName: "OT/IT Boundary Controls", enforcement: "soft" },
    ],
  },
  {
    name: "Predictive Maintenance Team",
    description: "Multi-agent predictive maintenance pipeline that monitors equipment sensor telemetry, predicts failure probabilities, schedules maintenance windows, and manages spare parts inventory. Reduces unplanned downtime through data-driven maintenance planning.",
    category: "team_workflow",
    industry: "manufacturing",
    tags: ["team", "predictive-maintenance", "multi-agent", "iot", "sequential"],
    icon: "users",
    complexity: "medium",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "MEDIUM",
    defaultAutonomyMode: "assisted",
    complianceCertifications: ["ISO-9001", "IEC-62443"],
    deploymentCount: 10,
    avgKpiDelivery: 85,
    estimatedTimeToProd: "3-5 weeks",
    toolsConfig: [
      { name: "sensor_telemetry_reader", description: "Reads real-time sensor data from equipment IoT endpoints", permissions: ["telemetry:read"] },
      { name: "failure_prediction_model", description: "Executes ML models for remaining useful life and failure probability", permissions: ["ml_models:invoke"] },
      { name: "maintenance_scheduler", description: "Schedules maintenance windows based on production calendars and criticality", permissions: ["schedules:write"] },
      { name: "parts_inventory_manager", description: "Checks and reserves spare parts inventory for planned maintenance", permissions: ["inventory:read", "inventory:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Sensor Monitoring Agent", role: "monitoring", skills: ["telemetry-ingestion", "anomaly-detection", "threshold-alerting"] },
        { name: "Failure Prediction Agent", role: "prediction", skills: ["rul-estimation", "failure-probability", "degradation-modeling"] },
        { name: "Maintenance Scheduler Agent", role: "scheduling", skills: ["window-optimization", "priority-ranking", "resource-allocation"] },
        { name: "Parts Inventory Agent", role: "logistics", skills: ["parts-lookup", "reorder-triggering", "supplier-coordination"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "OT/IT Data Boundary Enforcement", description: "Operational technology data separated from IT systems with controlled interfaces", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
        { name: "Safety-Critical Data Isolation", description: "Safety-critical data isolated from general analytics to prevent unauthorized access", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
        { name: "IP Protection for Process Parameters", description: "Intellectual property and proprietary process parameters encrypted and access-controlled", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
        { name: "Air-Gap Compliance for Classified Data", description: "Classified manufacturing data maintained in air-gapped environments with no external agent access", enforcement: "MODERATE", regulation: "IEC 62443 / ITAR" },
      ],
      federationTrust: {
        trustTier: "VERIFIED",
        requirements: [
          { name: "IP Protection Agreement", description: "Intellectual property protection agreement for manufacturing process data", status: "required", documentType: "Legal Agreement" },
          { name: "Export Control Compliance (ITAR/EAR)", description: "Compliance with ITAR and EAR export control regulations", status: "required", documentType: "Compliance Document" },
          { name: "On-Premise Deployment Option", description: "On-premise deployment option required for classified manufacturing work", status: "recommended", documentType: "Technical Specification" },
          { name: "Supply Chain Security Attestation", description: "Supply chain security attestation for hardware and software components", status: "optional", documentType: "Attestation" },
        ],
      },
    },
    policyBindings: [
      { policyName: "Equipment Safety Standards", enforcement: "hard" },
      { policyName: "OT/IT Boundary Controls", enforcement: "hard" },
      { policyName: "Maintenance Documentation Standards", enforcement: "soft" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // INSURANCE (2 team templates)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Claims Processing Team",
    description: "Automated claims lifecycle management from first notice of loss through coverage verification, adjudication, and fraud screening. Ensures regulatory compliance with state insurance laws while accelerating settlement timelines.",
    category: "team_workflow",
    industry: "insurance",
    tags: ["team", "claims-processing", "multi-agent", "fraud-detection", "sequential"],
    icon: "users",
    complexity: "high",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "HIGH",
    defaultAutonomyMode: "assisted",
    complianceCertifications: ["SOC2", "NAIC-MDL"],
    deploymentCount: 20,
    avgKpiDelivery: 90,
    estimatedTimeToProd: "3-5 weeks",
    toolsConfig: [
      { name: "fnol_intake_system", description: "Receives and processes first notice of loss submissions", permissions: ["claims:write"] },
      { name: "policy_coverage_checker", description: "Validates claims against policy coverage terms, limits, and exclusions", permissions: ["policies:read"] },
      { name: "damage_assessment_engine", description: "Calculates damage estimates and reserve amounts based on claim details", permissions: ["settlements:compute"] },
      { name: "fraud_pattern_scanner", description: "Scans claims against known fraud patterns and anomaly indicators", permissions: ["fraud_models:invoke"] },
      { name: "claims_status_updater", description: "Updates claim status and generates settlement recommendations", permissions: ["claims:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "FNOL Agent", role: "intake", skills: ["claim-registration", "loss-documentation", "coverage-lookup"] },
        { name: "Coverage Verification Agent", role: "verification", skills: ["policy-validation", "coverage-determination", "exclusion-check"] },
        { name: "Adjudication Agent", role: "assessment", skills: ["damage-assessment", "reserve-setting", "settlement-calculation"] },
        { name: "Fraud Screening Agent", role: "fraud-detection", skills: ["pattern-detection", "anomaly-scoring", "siu-referral"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "Claims Data Isolation from Underwriting", description: "Claims processing data strictly separated from underwriting decision agents", enforcement: "STRICT", regulation: "State Insurance Laws" },
        { name: "Anti-Fraud Data Segregation", description: "Fraud detection data and signals segregated from standard claims processing", enforcement: "STRICT", regulation: "State Insurance Laws" },
        { name: "Policyholder PII Minimization", description: "Policyholder personally identifiable information minimized across agent handoffs", enforcement: "STRICT", regulation: "State Insurance Laws" },
        { name: "Reinsurance Data Boundaries", description: "Reinsurance data boundaries enforced to prevent data leakage between cedant and reinsurer agents", enforcement: "STRICT", regulation: "State Insurance Laws" },
      ],
      federationTrust: {
        trustTier: "VERIFIED",
        requirements: [
          { name: "Data Processing Agreement", description: "Data processing agreement covering policyholder and claims data", status: "required", documentType: "Legal Agreement" },
          { name: "Actuarial Model Validation", description: "External actuarial models must be validated against industry standards", status: "recommended", documentType: "Validation Report" },
          { name: "Claims Data Handling Certification", description: "Certification for proper handling and storage of claims data", status: "required", documentType: "Certification" },
          { name: "State Regulatory Compliance Attestation", description: "Attestation of compliance with applicable state insurance regulations", status: "required", documentType: "Attestation" },
        ],
      },
    },
    policyBindings: [
      { policyName: "Claims Handling Best Practices", enforcement: "hard" },
      { policyName: "Anti-Fraud Screening Requirements", enforcement: "hard" },
      { policyName: "Settlement Authority Limits", enforcement: "hard" },
    ],
  },
  {
    name: "Underwriting Assessment Team",
    description: "Multi-agent underwriting pipeline that evaluates risk exposures, validates application data, performs actuarial pricing, and generates binding recommendations. Supports both personal and commercial lines with configurable risk appetite parameters.",
    category: "team_workflow",
    industry: "insurance",
    tags: ["team", "underwriting", "multi-agent", "risk-assessment", "sequential"],
    icon: "users",
    complexity: "high",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "HIGH",
    defaultAutonomyMode: "manual",
    complianceCertifications: ["SOC2", "NAIC-MDL"],
    deploymentCount: 14,
    avgKpiDelivery: 86,
    estimatedTimeToProd: "4-6 weeks",
    toolsConfig: [
      { name: "application_data_validator", description: "Validates and enriches insurance application data from multiple sources", permissions: ["applications:read"] },
      { name: "risk_exposure_analyzer", description: "Analyzes risk exposures using actuarial models and external data", permissions: ["risk_models:invoke", "external_data:read"] },
      { name: "pricing_engine", description: "Calculates premium pricing based on risk assessment and rate tables", permissions: ["pricing:compute"] },
      { name: "underwriting_decision_writer", description: "Writes underwriting decisions, conditions, and binding recommendations", permissions: ["decisions:write"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Application Intake Agent", role: "intake", skills: ["data-validation", "application-enrichment", "duplicate-detection"] },
        { name: "Risk Assessment Agent", role: "assessment", skills: ["exposure-analysis", "loss-history-review", "hazard-identification"] },
        { name: "Actuarial Pricing Agent", role: "pricing", skills: ["rate-calculation", "experience-modification", "premium-optimization"] },
        { name: "Binding Decision Agent", role: "decision", skills: ["authority-validation", "condition-setting", "referral-routing"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "Claims Data Isolation from Underwriting", description: "Claims processing data strictly separated from underwriting decision agents", enforcement: "STRICT", regulation: "State Insurance Laws" },
        { name: "Anti-Fraud Data Segregation", description: "Fraud detection data and signals segregated from standard claims processing", enforcement: "STRICT", regulation: "State Insurance Laws" },
        { name: "Policyholder PII Minimization", description: "Policyholder personally identifiable information minimized across agent handoffs", enforcement: "STRICT", regulation: "State Insurance Laws" },
        { name: "Reinsurance Data Boundaries", description: "Reinsurance data boundaries enforced to prevent data leakage between cedant and reinsurer agents", enforcement: "STRICT", regulation: "State Insurance Laws" },
      ],
      federationTrust: {
        trustTier: "VERIFIED",
        requirements: [
          { name: "Data Processing Agreement", description: "Data processing agreement covering policyholder and claims data", status: "required", documentType: "Legal Agreement" },
          { name: "Actuarial Model Validation", description: "External actuarial models must be validated against industry standards", status: "recommended", documentType: "Validation Report" },
          { name: "Claims Data Handling Certification", description: "Certification for proper handling and storage of claims data", status: "required", documentType: "Certification" },
          { name: "State Regulatory Compliance Attestation", description: "Attestation of compliance with applicable state insurance regulations", status: "required", documentType: "Attestation" },
        ],
      },
    },
    policyBindings: [
      { policyName: "Underwriting Authority Limits", enforcement: "hard" },
      { policyName: "Rate Filing Compliance", enforcement: "hard" },
      { policyName: "Unfair Discrimination Prevention", enforcement: "hard" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // RETAIL (2 team templates)
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Order Fulfillment Team",
    description: "End-to-end order processing pipeline from validation and payment verification through inventory allocation, fulfillment execution, and customer notification. Optimizes shipping carrier selection and provides real-time tracking updates.",
    category: "team_workflow",
    industry: "retail",
    tags: ["team", "order-fulfillment", "multi-agent", "logistics", "sequential"],
    icon: "users",
    complexity: "medium",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "LOW",
    defaultAutonomyMode: "autonomous",
    complianceCertifications: ["PCI-DSS", "SOC2"],
    deploymentCount: 25,
    avgKpiDelivery: 94,
    estimatedTimeToProd: "2-3 weeks",
    toolsConfig: [
      { name: "order_validation_engine", description: "Validates order details, payment authorization, and address verification", permissions: ["orders:read", "payments:verify"] },
      { name: "inventory_management_system", description: "Checks stock availability and allocates inventory across warehouses", permissions: ["inventory:read", "inventory:write"] },
      { name: "shipping_optimization_api", description: "Selects optimal carrier and shipping method based on cost, speed, and destination", permissions: ["shipping:compute"] },
      { name: "customer_notification_service", description: "Sends order confirmations, shipping updates, and delivery notifications", permissions: ["notifications:send"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Order Validation Agent", role: "validation", skills: ["order-verification", "payment-validation", "inventory-check"] },
        { name: "Inventory Agent", role: "inventory", skills: ["stock-allocation", "warehouse-routing", "backorder-management"] },
        { name: "Fulfillment Agent", role: "fulfillment", skills: ["pick-pack", "shipping-optimization", "carrier-selection"] },
        { name: "Customer Notification Agent", role: "communication", skills: ["order-updates", "delivery-tracking", "satisfaction-survey"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "PCI Data Scope Minimization", description: "Payment card data scope minimized across agent pipeline to reduce PCI compliance surface", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
        { name: "Customer Behavioral Data Compartmentalization", description: "Customer behavioral and browsing data compartmentalized from transaction processing agents", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
        { name: "Pricing Data Isolation", description: "Internal pricing and margin data isolated from customer-facing agents", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
        { name: "Inventory Data Freshness Enforcement", description: "Inventory data freshness enforced with maximum staleness thresholds between agents", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
      ],
      federationTrust: {
        trustTier: "STANDARD",
        requirements: [
          { name: "Data Processing Agreement", description: "Standard data processing agreement for customer and transaction data", status: "required", documentType: "Legal Agreement" },
          { name: "PCI Compliance Attestation", description: "PCI DSS compliance attestation for any payment data handling", status: "required", documentType: "Attestation" },
          { name: "CCPA/GDPR Data Handling Agreement", description: "Data handling agreement covering consumer privacy regulations", status: "recommended", documentType: "Legal Agreement" },
          { name: "API Rate Limiting SLA", description: "Service level agreement for API rate limiting and availability", status: "optional", documentType: "SLA" },
        ],
      },
    },
    policyBindings: [
      { policyName: "PCI-DSS Data Handling", enforcement: "hard" },
      { policyName: "Order Processing SLA", enforcement: "soft" },
      { policyName: "Customer Communication Standards", enforcement: "soft" },
    ],
  },
  {
    name: "Customer Experience Team",
    description: "Multi-agent customer experience pipeline that handles inquiry routing, sentiment analysis, personalized recommendation generation, and escalation management. Provides omnichannel support with consistent brand voice across all touchpoints.",
    category: "team_workflow",
    industry: "retail",
    tags: ["team", "customer-experience", "multi-agent", "support", "sequential"],
    icon: "users",
    complexity: "medium",
    modelProvider: "openai",
    modelName: "gpt-4.1",
    defaultRiskTier: "LOW",
    defaultAutonomyMode: "autonomous",
    complianceCertifications: ["PCI-DSS", "SOC2"],
    deploymentCount: 19,
    avgKpiDelivery: 91,
    estimatedTimeToProd: "2-3 weeks",
    toolsConfig: [
      { name: "inquiry_router", description: "Routes customer inquiries to appropriate handling agents based on intent classification", permissions: ["inquiries:read"] },
      { name: "sentiment_analysis_engine", description: "Analyzes customer sentiment in real-time across communication channels", permissions: ["analytics:compute"] },
      { name: "recommendation_engine", description: "Generates personalized product recommendations based on customer history", permissions: ["recommendations:compute", "customer_profiles:read"] },
      { name: "escalation_manager", description: "Manages escalation workflows and routes to human agents when needed", permissions: ["escalations:write", "notifications:send"] },
    ],
    blueprintJson: {
      templateType: "team",
      agents: [
        { name: "Inquiry Routing Agent", role: "routing", skills: ["intent-classification", "channel-detection", "priority-assignment"] },
        { name: "Sentiment Analysis Agent", role: "analysis", skills: ["sentiment-scoring", "emotion-detection", "churn-risk-assessment"] },
        { name: "Personalization Agent", role: "recommendation", skills: ["product-recommendation", "offer-personalization", "cross-sell-optimization"] },
        { name: "Escalation Manager Agent", role: "escalation", skills: ["escalation-routing", "supervisor-notification", "resolution-tracking"] },
      ],
      handoffPattern: "sequential",
      dataFlowGovernance: [
        { name: "PCI Data Scope Minimization", description: "Payment card data scope minimized across agent pipeline to reduce PCI compliance surface", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
        { name: "Customer Behavioral Data Compartmentalization", description: "Customer behavioral and browsing data compartmentalized from transaction processing agents", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
        { name: "Pricing Data Isolation", description: "Internal pricing and margin data isolated from customer-facing agents", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
        { name: "Inventory Data Freshness Enforcement", description: "Inventory data freshness enforced with maximum staleness thresholds between agents", enforcement: "MODERATE", regulation: "PCI DSS / CCPA" },
      ],
      federationTrust: {
        trustTier: "STANDARD",
        requirements: [
          { name: "Data Processing Agreement", description: "Standard data processing agreement for customer and transaction data", status: "required", documentType: "Legal Agreement" },
          { name: "PCI Compliance Attestation", description: "PCI DSS compliance attestation for any payment data handling", status: "required", documentType: "Attestation" },
          { name: "CCPA/GDPR Data Handling Agreement", description: "Data handling agreement covering consumer privacy regulations", status: "recommended", documentType: "Legal Agreement" },
          { name: "API Rate Limiting SLA", description: "Service level agreement for API rate limiting and availability", status: "optional", documentType: "SLA" },
        ],
      },
    },
    policyBindings: [
      { policyName: "CCPA Consumer Privacy", enforcement: "hard" },
      { policyName: "Customer Data Retention", enforcement: "soft" },
      { policyName: "Brand Voice Guidelines", enforcement: "soft" },
    ],
  },
];
