import { Router, type Request, type Response } from "express";

const router = Router();

router.get("/pipeline-summaries", (_req: Request, res: Response) => {
  res.json({
    success: true,
    reportDate: new Date().toISOString().split("T")[0],
    agentSummaries: {
      dataQuality: {
        agentCode: "BB-AGT-001",
        status: "complete",
        totalTransactions: 142183,
        quarantined: 23,
        fraudPatternsDetected: 1,
        anomalyDetectionRate: 97.2,
        topAnomalousSegments: ["Mid-Size Car", "Luxury SUV", "Full-Size Pickup"],
      },
      marketShifts: {
        agentCode: "BB-AGT-002",
        status: "complete",
        activeAlerts: 1,
        amberAlerts: [{ segment: "Full-Size Pickup", confidence: 0.87, leadTime: "2.5 weeks" }],
        portfolioOverallDirection: "Mixed — 7/12 segments depreciating, led by Full-Size Pickups (-1.8%/week)",
      },
      competitiveIntelligence: {
        agentCode: "BB-AGT-003",
        status: "complete",
        overallCompetitivePosition: "STRONG",
        keyWin: "Full-Size Pickup depreciation call 2.5 weeks ahead of KBB/NADA",
        divergenceScore: 4.2,
        dataFreshnessAdvantage: "30-day lead vs NADA on truck segment",
      },
    },
  });
});

router.get("/draft-market-summary", (_req: Request, res: Response) => {
  const weekOf = new Date().toISOString().split("T")[0];
  res.json({
    success: true,
    section: "Market Summary",
    wordCount: 187,
    draftText: `The wholesale vehicle market experienced mixed performance this week, with overall average values declining 0.3% week-over-week. Seven of twelve tracked segments showed depreciation, led by Full-Size Pickups (−1.8%) and Compact Cars (−0.9%). The Luxury Crossover/SUV segment was the strongest performer this week, appreciating 0.4% amid constrained auction supply.\n\nTotal auction volume across Black Book's 142,000+ daily transaction feed remained robust, though Full-Size Pickup supply surged 22% above the four-week average — a pattern consistent with fleet operator liquidation ahead of new model year arrivals. Black Book's multi-signal detection system flagged this shift with 87% confidence 2.5 weeks ahead of expected surfacing in traditional weekly reports.\n\nWeek of ${weekOf}. All values reflect Black Book wholesale market data from Manheim, Adesa, and independent auction sources.`,
    autoGeneratedPct: 100,
    analystActionRequired: false,
  });
});

router.get("/draft-segment-analysis", (_req: Request, res: Response) => {
  res.json({
    success: true,
    section: "Segment Analysis",
    segments: [
      {
        segment: "Full-Size Pickup",
        weeklyChange: -1.8,
        fourWeekChange: -5.1,
        autoText: "Full-Size Pickups continued their depreciation trajectory this week, declining 1.8% — more than four times the historical weekly norm of 0.4%. The Black Book Market Shift Detector fused four independent signals: a 22% auction volume surge (fleet liquidation), new OEM incentives on the 2024 F-150 and Silverado, a 35¢/gallon fuel price decline reducing the truck premium, and negative sentiment in logistics sector news. Black Book projects an additional 1.8–2.5% decline over the next two weeks. Lenders with Full-Size Pickup concentration should review advance rates.",
        alertLevel: "AMBER",
        analystHighlightRequired: true,
        confidence: 0.87,
      },
      {
        segment: "Luxury SUV",
        weeklyChange: 0.4,
        fourWeekChange: 1.1,
        autoText: "Luxury SUVs were the week's outperformers, appreciating 0.4% on reduced auction supply. Volume at Manheim and Adesa combined declined 9.2% vs. the four-week average, tightening inventory for the segment. Consumer demand for Luxury SUVs remains resilient. No adverse signals detected.",
        alertLevel: null,
        analystHighlightRequired: false,
      },
      {
        segment: "Electric Vehicle",
        weeklyChange: -0.9,
        fourWeekChange: -2.4,
        autoText: "EV wholesale values declined 0.9% this week, slightly above the category's historical depreciation norm of 0.5%. Charging infrastructure expansion and potential tax credit extensions are supporting demand, partially offsetting residual value pressure. Black Book continues to maintain a conservative EV outlook given persistent residual value volatility.",
        alertLevel: "YELLOW",
        analystHighlightRequired: false,
      },
      {
        segment: "Mid-Size SUV",
        weeklyChange: 0.3,
        fourWeekChange: 0.2,
        autoText: "Mid-Size SUVs held steady this week with a marginal 0.3% gain. Demand remains balanced. No significant supply or demand disruptions detected.",
        alertLevel: null,
        analystHighlightRequired: false,
      },
    ],
  });
});

router.get("/finalize-report", (_req: Request, res: Response) => {
  res.json({
    success: true,
    reportId: `WR-${new Date().toISOString().split("T")[0].replace(/-/g, "")}`,
    reportTitle: "Black Book Weekly Wholesale Insights",
    weekOf: new Date().toISOString().split("T")[0],
    status: "DRAFT — Ready for analyst review",
    sections: [
      { name: "Market Summary", status: "auto-generated", wordCount: 187, analystReviewRequired: false },
      { name: "Segment Analysis", status: "auto-generated", wordCount: 412, analystReviewRequired: true, highlightedSegments: ["Full-Size Pickup"] },
      { name: "Anomaly Report", status: "auto-generated", wordCount: 156, analystReviewRequired: true, reason: "Suspected fraud pattern requires analyst sign-off before publication" },
      { name: "Competitive Intelligence Brief", status: "auto-generated", wordCount: 203, analystReviewRequired: false },
      { name: "Residual Value Outlook", status: "partially-generated", wordCount: 89, analystReviewRequired: true, reason: "Analyst to add expert commentary on EV residual outlook" },
    ],
    metrics: {
      totalWordCount: 1047,
      autoGeneratedWordCount: 897,
      autoGeneratedPct: 85.7,
      generationTimeSec: 187,
      analystTimeSavedHours: 8.5,
      sectionsAutoComplete: 3,
      sectionsNeedingReview: 2,
    },
    subscribers: 15000,
    publishTarget: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
  });
});

export default router;
