// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/business-mode/CommandCenter.tsx": () => import("../components/mockups/business-mode/CommandCenter.tsx"),
  "./components/mockups/business-mode/MyActions.tsx": () => import("../components/mockups/business-mode/MyActions.tsx"),
  "./components/mockups/business-mode/Outcomes.tsx": () => import("../components/mockups/business-mode/Outcomes.tsx"),
  "./components/mockups/business-mode/SidebarComparison.tsx": () => import("../components/mockups/business-mode/SidebarComparison.tsx")
};
