import { useQuery } from "@tanstack/react-query";
import { FileText, Clock, Users, CheckCircle2, AlertCircle, Loader2, Bot } from "lucide-react";

interface ReportData {
  success: boolean;
  reportId: string;
  reportTitle: string;
  weekOf: string;
  status: string;
  sections: { name: string; status: string; wordCount: number; analystReviewRequired: boolean; reason?: string; highlightedSegments?: string[] }[];
  metrics: { totalWordCount: number; autoGeneratedWordCount: number; autoGeneratedPct: number; generationTimeSec: number; analystTimeSavedHours: number; sectionsAutoComplete: number; sectionsNeedingReview: number };
  subscribers: number;
  publishTarget: string;
}

interface MarketSummaryData {
  success: boolean;
  section: string;
  wordCount: number;
  draftText: string;
  autoGeneratedPct: number;
}

interface SegmentData {
  success: boolean;
  section: string;
  segments: { segment: string; weeklyChange: number; fourWeekChange: number; autoText: string; alertLevel: string | null; analystHighlightRequired: boolean; confidence: number }[];
}

export default function BBScreen4WeeklyReport({ pipelineComplete = false }: { pipelineComplete?: boolean }) {
  const { data: reportData, isLoading: rLoading } = useQuery<ReportData>({
    queryKey: ["/api/mock/bb-report-engine/finalize-report"],
    refetchInterval: 60000,
    enabled: pipelineComplete,
  });

  const { data: summaryData, isLoading: sLoading } = useQuery<MarketSummaryData>({
    queryKey: ["/api/mock/bb-report-engine/draft-market-summary"],
    refetchInterval: 60000,
    enabled: pipelineComplete,
  });

  const { data: segData, isLoading: segLoading } = useQuery<SegmentData>({
    queryKey: ["/api/mock/bb-report-engine/draft-segment-analysis"],
    refetchInterval: 60000,
    enabled: pipelineComplete,
  });

  if (!pipelineComplete || rLoading || sLoading || segLoading) {
    const msg = !pipelineComplete
      ? "Waiting for agent pipeline to complete…"
      : "Agent compiling weekly valuation report…";
    return (
      <div className="flex items-center justify-center h-48">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="w-4 h-4 animate-spin" />
          {msg}
        </div>
      </div>
    );
  }

  const report = reportData!;
  const summary = summaryData!;
  const segments = segData!;

  return (
    <div className="space-y-4">
      {/* Report header */}
      <div className="rounded-xl border bg-card p-5" data-testid="bb-report-header">
        <div className="flex items-start justify-between gap-4">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <FileText className="w-4 h-4 text-muted-foreground" />
              <span className="text-[10px] text-muted-foreground font-mono">{report.reportId}</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full border border-amber-500/30 bg-amber-500/10 text-amber-400">{report.status}</span>
            </div>
            <h2 className="text-base font-bold">{report.reportTitle}</h2>
            <p className="text-xs text-muted-foreground mt-0.5">Week of {report.weekOf} · Publishing to {report.subscribers.toLocaleString()} subscribers on {report.publishTarget}</p>
          </div>

          <div className="flex gap-5 shrink-0 text-right">
            <div>
              <div className="flex items-center gap-1 text-muted-foreground justify-end mb-0.5">
                <Bot className="w-3.5 h-3.5" />
                <span className="text-[10px]">Auto-generated</span>
              </div>
              <p className="text-2xl font-bold text-green-400">{report.metrics.autoGeneratedPct.toFixed(0)}%</p>
              <p className="text-[10px] text-muted-foreground">of {report.metrics.totalWordCount.toLocaleString()} words</p>
            </div>
            <div>
              <div className="flex items-center gap-1 text-muted-foreground justify-end mb-0.5">
                <Clock className="w-3.5 h-3.5" />
                <span className="text-[10px]">Time saved</span>
              </div>
              <p className="text-2xl font-bold">{report.metrics.analystTimeSavedHours}h</p>
              <p className="text-[10px] text-muted-foreground">per week</p>
            </div>
            <div>
              <div className="flex items-center gap-1 text-muted-foreground justify-end mb-0.5">
                <Clock className="w-3.5 h-3.5" />
                <span className="text-[10px]">Draft generated</span>
              </div>
              <p className="text-2xl font-bold">{Math.round(report.metrics.generationTimeSec / 60)}min</p>
              <p className="text-[10px] text-muted-foreground">{report.metrics.generationTimeSec}s total</p>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-4">
        {/* Section status */}
        <div className="space-y-2">
          <h3 className="text-xs font-semibold">Report Sections</h3>
          {report.sections.map(section => (
            <div key={section.name} className={`p-3 rounded-lg border ${section.analystReviewRequired ? "border-amber-500/30 bg-amber-500/5" : "border-border/50 bg-muted/10"}`} data-testid={`bb-report-section-${section.name.replace(/\s/g,"-").toLowerCase()}`}>
              <div className="flex items-start gap-2">
                {section.analystReviewRequired
                  ? <AlertCircle className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
                  : <CheckCircle2 className="w-3.5 h-3.5 text-green-400 shrink-0 mt-0.5" />}
                <div className="flex-1 min-w-0">
                  <p className="text-[11px] font-semibold leading-tight">{section.name}</p>
                  <div className="flex items-center gap-1.5 mt-0.5">
                    <span className={`text-[9px] px-1 py-0.5 rounded ${section.status === "auto-generated" ? "bg-green-500/10 text-green-400" : section.status === "partially-generated" ? "bg-amber-500/10 text-amber-400" : "bg-muted/50 text-muted-foreground"}`}>
                      {section.status}
                    </span>
                    <span className="text-[9px] text-muted-foreground">{section.wordCount} words</span>
                  </div>
                  {section.reason && <p className="text-[9px] text-amber-400 mt-0.5">{section.reason}</p>}
                  {section.highlightedSegments && <p className="text-[9px] text-muted-foreground mt-0.5">Alert: {section.highlightedSegments.join(", ")}</p>}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Market summary draft */}
        <div className="col-span-2 space-y-3">
          <div className="rounded-xl border bg-card p-4" data-testid="bb-market-summary-draft">
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-xs font-semibold">Section 1: Market Summary</h3>
              <div className="flex items-center gap-2">
                <span className="text-[10px] text-muted-foreground">{summary.wordCount} words</span>
                <span className="text-[10px] px-1.5 py-0.5 rounded bg-green-500/10 text-green-400 border border-green-500/20">100% auto-generated</span>
              </div>
            </div>
            <p className="text-[11px] leading-relaxed text-foreground/80 whitespace-pre-line">{summary.draftText}</p>
          </div>

          {/* Segment highlights */}
          <div className="rounded-xl border bg-card p-4">
            <h3 className="text-xs font-semibold mb-3">Section 2: Segment Analysis (Highlights)</h3>
            <div className="space-y-3">
              {segments.segments?.map(seg => (
                <div key={seg.segment} className={`p-3 rounded-lg border ${seg.alertLevel === "AMBER" ? "border-amber-500/30 bg-amber-500/5" : "border-border/50 bg-muted/10"}`} data-testid={`bb-segment-draft-${seg.segment.replace(/\s/g,"-").toLowerCase()}`}>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <span className="text-[11px] font-semibold">{seg.segment}</span>
                      {seg.analystHighlightRequired && (
                        <span className="text-[9px] px-1.5 py-0.5 rounded border border-amber-500/30 bg-amber-500/10 text-amber-400">⚑ Analyst flag</span>
                      )}
                    </div>
                    <div className="flex items-center gap-2">
                      <span className={`text-[11px] font-bold tabular-nums ${seg.weeklyChange < 0 ? "text-red-400" : "text-green-400"}`}>
                        {seg.weeklyChange > 0 ? "+" : ""}{seg.weeklyChange}% WoW
                      </span>
                      <span className={`text-[10px] text-muted-foreground`}>
                        {seg.fourWeekChange > 0 ? "+" : ""}{seg.fourWeekChange}% 4-wk
                      </span>
                    </div>
                  </div>
                  <p className="text-[10px] text-foreground/80 leading-relaxed">{seg.autoText}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
