#!/usr/bin/env bash
# Provisions everything needed to run Astra Agents on Azure App Service:
# resource group, Postgres Flexible Server (+ pgvector), App Service plan +
# Web App, the three production-required secrets, app settings, WebSockets/
# Always On, and GitHub-linked continuous deployment.
#
# Safe to re-run — every `az ... create` call below is idempotent (no-ops or
# updates in place if the resource already exists).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if [ ! -f config.env ]; then
  echo "Missing config.env — copy config.env.example to config.env and fill it in first." >&2
  exit 1
fi
# shellcheck disable=SC1091
source config.env

for v in RG LOCATION DB_SERVER DB_NAME DB_ADMIN PLAN APP_NAME GITHUB_REPO_URL GITHUB_BRANCH ANTHROPIC_API_KEY OPENAI_API_KEY; do
  if [ -z "${!v:-}" ] || [[ "${!v}" == *REPLACE_ME* ]]; then
    echo "config.env: $v is not set (or still has its placeholder value) — fill it in and re-run." >&2
    exit 1
  fi
done

SECRETS_FILE=.generated-secrets.env

echo "=== 1/8: Resource group ==="
# A resource group's location is immutable once created — passing a
# different --location to `az group create` for an existing group is a hard
# error (InvalidResourceGroupLocation), not a no-op. If it already exists,
# leave it exactly where it is; the actual resources below (Postgres, App
# Service) are created with $LOCATION independently and don't need to match
# the resource group's own location.
EXISTING_RG_LOCATION=$(az group show --name "$RG" --query location -o tsv 2>/dev/null || true)
if [ -n "$EXISTING_RG_LOCATION" ]; then
  echo "  $RG already exists in '$EXISTING_RG_LOCATION' — leaving as-is. Resources below will still be created in '$LOCATION'."
else
  az group create --name "$RG" --location "$LOCATION" --output none
fi

echo "=== 2/8: Generating secrets ==="
if [ -f "$SECRETS_FILE" ]; then
  echo "  $SECRETS_FILE already exists — reusing it (delete it first if you want fresh secrets)."
  # shellcheck disable=SC1090
  source "$SECRETS_FILE"
else
  DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  JWT_SECRET=$(openssl rand -base64 48)
  INTEGRATION_VAULT_KEY=$(openssl rand -base64 32)
  ASTRA_PUBLIC_API_KEY="astra_$(openssl rand -hex 32)"

  AUDIT_KEY_PEM_FILE=$(mktemp)
  openssl genpkey -algorithm ed25519 -out "$AUDIT_KEY_PEM_FILE"
  AUDIT_SIGNING_PRIVATE_KEY=$(base64 -w 0 "$AUDIT_KEY_PEM_FILE" 2>/dev/null || base64 "$AUDIT_KEY_PEM_FILE" | tr -d '\n')
  rm -f "$AUDIT_KEY_PEM_FILE"

  cat > "$SECRETS_FILE" <<EOF
# Generated by provision.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — keep this file safe, never commit it.
DB_PASSWORD='$DB_PASSWORD'
JWT_SECRET='$JWT_SECRET'
INTEGRATION_VAULT_KEY='$INTEGRATION_VAULT_KEY'
AUDIT_SIGNING_PRIVATE_KEY='$AUDIT_SIGNING_PRIVATE_KEY'
ASTRA_PUBLIC_API_KEY='$ASTRA_PUBLIC_API_KEY'
EOF
  chmod 600 "$SECRETS_FILE"
  echo "  Wrote new secrets to $SECRETS_FILE (chmod 600). Back this up somewhere safe — the audit signing key in particular can't be regenerated without invalidating past signed audit events."
fi

DATABASE_URL="postgresql://${DB_ADMIN}:${DB_PASSWORD}@${DB_SERVER}.postgres.database.azure.com:5432/${DB_NAME}?sslmode=require"

echo "=== 3/8: Postgres Flexible Server (this step can take several minutes) ==="
if az postgres flexible-server show --resource-group "$RG" --name "$DB_SERVER" --output none 2>/dev/null; then
  echo "  $DB_SERVER already exists — skipping create."
else
  az postgres flexible-server create \
    --resource-group "$RG" \
    --name "$DB_SERVER" \
    --location "$LOCATION" \
    --admin-user "$DB_ADMIN" \
    --admin-password "$DB_PASSWORD" \
    --sku-name Standard_B1ms \
    --tier Burstable \
    --storage-size 32 \
    --version 16 \
    --public-access 0.0.0.0-255.255.255.255 \
    --output none
fi

az postgres flexible-server db create \
  --resource-group "$RG" \
  --server-name "$DB_SERVER" \
  --database-name "$DB_NAME" \
  --output none 2>/dev/null || echo "  Database $DB_NAME already exists — skipping."

echo "=== 4/8: Enabling pgvector ==="
az postgres flexible-server parameter set \
  --resource-group "$RG" --server-name "$DB_SERVER" \
  --name azure.extensions --value VECTOR \
  --output none

# `postgres flexible-server execute` ships in the rdbms-connect extension, not
# core az CLI -- not installed by default on Cloud Shell.
if ! az extension show --name rdbms-connect --output none 2>/dev/null; then
  echo "  Installing the rdbms-connect CLI extension (needed to run CREATE EXTENSION)..."
  az extension add --name rdbms-connect --only-show-errors
fi

az postgres flexible-server execute \
  --name "$DB_SERVER" --admin-user "$DB_ADMIN" --admin-password "$DB_PASSWORD" \
  --database-name "$DB_NAME" \
  --querytext "CREATE EXTENSION IF NOT EXISTS vector;" \
  --output none

echo "=== 5/8: App Service plan + Web App ==="
az appservice plan create \
  --resource-group "$RG" \
  --name "$PLAN" \
  --is-linux \
  --sku B1 \
  --output none 2>/dev/null || echo "  $PLAN already exists — skipping."

az webapp create \
  --resource-group "$RG" \
  --plan "$PLAN" \
  --name "$APP_NAME" \
  --runtime "NODE:22-lts" \
  --output none 2>/dev/null || echo "  $APP_NAME already exists — skipping."

echo "=== 6/8: App settings ==="
az webapp config appsettings set \
  --resource-group "$RG" --name "$APP_NAME" \
  --settings \
    NODE_ENV=production \
    SECURITY_MODE=production \
    DATABASE_URL="$DATABASE_URL" \
    JWT_SECRET="$JWT_SECRET" \
    INTEGRATION_VAULT_KEY="$INTEGRATION_VAULT_KEY" \
    AUDIT_SIGNING_PRIVATE_KEY="$AUDIT_SIGNING_PRIVATE_KEY" \
    ASTRA_PUBLIC_API_KEY="$ASTRA_PUBLIC_API_KEY" \
    DEFAULT_LLM_PROVIDER=anthropic \
    ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
    OPENAI_API_KEY="$OPENAI_API_KEY" \
    SCM_DO_BUILD_DURING_DEPLOYMENT=true \
    WEBSITE_NODE_DEFAULT_VERSION=~22 \
  --output none

echo "=== 7/8: WebSockets + Always On (needed for SSE streaming + the in-process job worker) ==="
az webapp config set \
  --resource-group "$RG" --name "$APP_NAME" \
  --web-sockets-enabled true \
  --always-on true \
  --startup-file "npm start" \
  --output none

echo "=== 8/8: GitHub-linked continuous deployment ==="
az webapp deployment source config \
  --resource-group "$RG" --name "$APP_NAME" \
  --repo-url "$GITHUB_REPO_URL" \
  --branch "$GITHUB_BRANCH" \
  --manual-integration \
  --output none

echo ""
echo "Done. https://${APP_NAME}.azurewebsites.net"
echo "Next: ./migrate.sh to push the DB schema, then ./verify.sh to confirm it's up."
echo ""
echo "NOTE: the Postgres firewall above is open to all IPs (0.0.0.0-255.255.255.255) so this"
echo "script runs end-to-end without extra steps. Tighten it once you're past initial setup:"
echo "  az postgres flexible-server firewall-rule delete --resource-group $RG --name $DB_SERVER --rule-name AllowAll"
echo "  az postgres flexible-server firewall-rule create --resource-group $RG --name $DB_SERVER --rule-name AllowAppService \\"
echo "    --start-ip-address <app-service-outbound-ip> --end-ip-address <app-service-outbound-ip>"
echo "  (get the IP list with: az webapp show --resource-group $RG --name $APP_NAME --query outboundIpAddresses --output tsv)"
