#!/usr/bin/env bash
# Provisions Azure Blob Storage for large media (video, and eventually any
# attachment past the 25MB Postgres-bytea ceiling in server/routes/files.ts)
# and wires the connection into the already-deployed Web App's app settings.
#
# Run this AFTER provision.sh/recover-secrets.sh have already set up
# config.env — it reads RG/LOCATION/APP_NAME from there, the same as every
# other script in this pack, rather than asking for them again.
#
# Safe to re-run: the storage account name is generated once and persisted to
# .media-storage.env (gitignored, same idea as .generated-secrets.env) so a
# second run reuses the same account instead of creating a new one every time.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Pulling latest from git..."
  git pull --ff-only || { echo "git pull failed -- resolve manually before continuing." >&2; exit 1; }
fi

if [ ! -f config.env ]; then
  echo "Missing config.env — run ./recover-secrets.sh <rg> <app-name> (or ./provision.sh for a brand new deployment) first." >&2
  exit 1
fi
# shellcheck disable=SC1091
source config.env

for v in RG LOCATION APP_NAME; do
  if [ -z "${!v:-}" ]; then
    echo "config.env: $v is not set — re-run ./recover-secrets.sh or ./provision.sh first." >&2
    exit 1
  fi
done

CONTAINER=media
STATE_FILE=.media-storage.env

echo "=== 1/4: Storage account ==="
if [ -f "$STATE_FILE" ]; then
  echo "  $STATE_FILE already exists — reusing its storage account name."
  # shellcheck disable=SC1090
  source "$STATE_FILE"
else
  # Storage account names are globally unique across ALL of Azure, lowercase
  # letters/digits only, <=24 chars -- derive from APP_NAME (which is already
  # globally unique for the same reason) plus a short random suffix so a
  # second app sharing the same prefix can't collide.
  BASE=$(echo "${APP_NAME}media" | tr -cd 'a-z0-9' | cut -c1-18)
  STORAGE_ACCOUNT="${BASE}$(openssl rand -hex 3)"
  cat > "$STATE_FILE" <<EOF
# Generated by provision-media-storage.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — keep this, delete only to force a new storage account.
STORAGE_ACCOUNT='$STORAGE_ACCOUNT'
EOF
  chmod 600 "$STATE_FILE"
  echo "  Chose new storage account name: $STORAGE_ACCOUNT (saved to $STATE_FILE)"
fi

if az storage account show --name "$STORAGE_ACCOUNT" --resource-group "$RG" --output none 2>/dev/null; then
  echo "  $STORAGE_ACCOUNT already exists — skipping create."
else
  az storage account create \
    --name "$STORAGE_ACCOUNT" \
    --resource-group "$RG" \
    --location "$LOCATION" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --access-tier Hot \
    --min-tls-version TLS1_2 \
    --allow-blob-public-access false \
    --output none
fi

STORAGE_KEY=$(az storage account keys list --account-name "$STORAGE_ACCOUNT" --resource-group "$RG" --query "[0].value" -o tsv)
STORAGE_CONNECTION_STRING=$(az storage account show-connection-string --name "$STORAGE_ACCOUNT" --resource-group "$RG" --query connectionString -o tsv)

echo "=== 2/4: Private media container ==="
if az storage container show --name "$CONTAINER" --account-name "$STORAGE_ACCOUNT" --account-key "$STORAGE_KEY" --output none 2>/dev/null; then
  echo "  Container '$CONTAINER' already exists — skipping."
else
  az storage container create \
    --name "$CONTAINER" \
    --account-name "$STORAGE_ACCOUNT" \
    --account-key "$STORAGE_KEY" \
    --public-access off \
    --output none
fi

echo "=== 3/4: CORS (lets the browser PUT/GET blobs directly, bypassing the app for the actual bytes) ==="
az storage cors clear --services b --account-name "$STORAGE_ACCOUNT" --account-key "$STORAGE_KEY" --output none
az storage cors add \
  --services b \
  --methods PUT GET HEAD OPTIONS \
  --origins "https://${APP_NAME}.azurewebsites.net" \
  --allowed-headers "*" \
  --exposed-headers "*" \
  --max-age 3600 \
  --account-name "$STORAGE_ACCOUNT" --account-key "$STORAGE_KEY" \
  --output none

echo "=== 4/4: Wiring into the Web App's app settings ==="
az webapp config appsettings set \
  --resource-group "$RG" --name "$APP_NAME" \
  --settings \
    AZURE_STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION_STRING" \
    AZURE_STORAGE_CONTAINER="$CONTAINER" \
    MEDIA_MAX_UPLOAD_MB=200 \
  --output none

echo ""
echo "Done. $STORAGE_ACCOUNT / container '$CONTAINER' is wired into $APP_NAME."
echo "Setting app settings restarts the app automatically -- no separate restart needed."
echo ""
echo "Optional -- auto-delete media older than 30 days (keeps demo clutter and cost down):"
echo "  az storage account management-policy create --account-name $STORAGE_ACCOUNT -g $RG --policy '{\"rules\":[{\"name\":\"expire-media\",\"enabled\":true,\"type\":\"Lifecycle\",\"definition\":{\"filters\":{\"blobTypes\":[\"blockBlob\"],\"prefixMatch\":[\"${CONTAINER}/\"]},\"actions\":{\"baseBlob\":{\"delete\":{\"daysAfterModificationGreaterThan\":30}}}}}]}'"
echo ""
echo "Next: the app code that actually uses this (SAS-issuing endpoint + direct-upload path) is still to be built and deployed -- do NOT expect video uploads over 25MB to work until that ships."
